backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://site-en-developpement-aamc.netlify.app/
display_url: 
logo_url: 
locale: 'fr'

media_folder: assets/img
public_folder: /img
collections:
  - name: 'articles'
    label: 'Mes Articles'
    description: 'Modifiez des articles existants, ou en créer de nouveaux'
    folder: 'content/posts'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Intitulé Article et Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est lintitulé de cet article sur le site + le titre SEO de votre page' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparaitra depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Résumé article', name: 'summary', widget: 'string', hint: 'Ceci est le Résumé de votre article qui apparaitra en première page du site + soyez bref et donnez envie au lecteur de cliquer et ouvrir article' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + parlez de votre prestation + ajoutez une ou deux photos si nécessaire + soyez concis mais percutant + pensez à introduire vos mots clés' }

  - name: "pagesprincipales"
    label: "Pages Principales"
    files:
      - name: 'raisondetre'
        label: 'Raison d'être'
        description: 'Modifiez ici la page Raison dêtre'
        file: 'content/raison-detre.md'
        editor:
          preview: true
        fields:
      - { label: 'Intitulé Article et Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est lintitulé de cet article sur le site + le titre SEO de votre page' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparaitra depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + parlez de votre prestation + ajoutez une ou deux photos si nécessaire + soyez concis mais percutant + pensez à introduire vos mots clés' }
      - name: 'activites'
        label: 'Activités'
        description: 'Modifiez ici la page Activités'
        file: 'content/activites.md'
        editor:
          preview: true
        fields:
      - { label: 'Intitulé Article et Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est lintitulé de cet article sur le site + le titre SEO de votre page' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparaitra depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + parlez de votre prestation + ajoutez une ou deux photos si nécessaire + soyez concis mais percutant + pensez à introduire vos mots clés' }
      - name: 'gallerie'
        label: 'Gallerie'
        description: 'Modifiez ici la page Gallerie'
        file: 'content/gallerie.md'
        editor:
          preview: true
        fields:
      - { label: 'Intitulé Article et Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est lintitulé de cet article sur le site + le titre SEO de votre page' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparaitra depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + parlez de votre prestation + ajoutez une ou deux photos si nécessaire + soyez concis mais percutant + pensez à introduire vos mots clés' }
      - name: 'contact'
        label: 'Contact'
        description: 'Modifiez ici la page Contact'
        file: 'content/contact.md'
        editor:
          preview: true
        fields:
      - { label: 'Intitulé Article et Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est lintitulé de cet article sur le site + le titre SEO de votre page' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparaitra depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + parlez de votre prestation + ajoutez une ou deux photos si nécessaire + soyez concis mais percutant + pensez à introduire vos mots clés' }
      - name: 'mentionslegales'
        label: 'Mentions Légales'
        description: 'Modifiez ici la page Mentions Légales'
        file: 'content/mentionslegales.md'
        editor:
          preview: true
        fields:
          - { label: 'Intitulé Article et Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est lintitulé de cet article sur le site + le titre SEO de votre page' }
          - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparaitra depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
          - { label: 'Adresse email', name: 'email', widget: 'string', hint: 'Modifiez si nécessaire adresse email de la page Contact' }
          - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + parlez de votre prestation + ajoutez une ou deux photos si nécessaire + soyez concis mais percutant + pensez à introduire vos mots clés' }
